### ISSUE TITLE
SOME/IP feeder needs support for streaming datapoints to datakbroker

### ISSUE THREAD

**Issue by int0x27** [eclipse/kuksa.val.feeders#102]
We need  better performance on cyclic updates, especially with authentication involved.

Implement [Collector.StreamDatapoints()](https://github.com/eclipse/kuksa.val/blob/13900d63cf8e6dd1d9eccb91e3cceabb7a4a8e72/kuksa_databroker/proto/sdv/databroker/v1/collector.proto#LL59C7-L59C23) to optimize CPU usage and avoid very frequent context creation

**Comment by erikbosch** [comment]
No one seems to be that interested in fixing this, closing this for now. Reopen if wanted.
