### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by MathiasDanzeisen** [eclipse/kuksa.val.feeders#107]
When using the feeders you to might avoid having a flowting target and therefore depending with your project on this main branch might be not always prefared.
Since the last release was already in the beginning of feb I think it is time for another release with all the improvments.

**Comment by erikbosch** [comment]
I agree that having a release would be good. But at least for the Python-based feeders we first should better have a release or at least tagging of the KUKSA.val repo so we could have a pypi release of kuksa-client and also test against released versions of KUKSA.val.

@SebastianSchildt - should we possibly plan for a release

**Comment by erikbosch** [comment]
Work is ongoing to release v0.4.0. As a first step for kuksa.val, as a second step for this repo

**Comment by SebastianSchildt** [comment]
0.4 is out and meanwhile there should also be master/main builds for most components
