### ISSUE TITLE
Align Feeder/Provider names

### ISSUE THREAD

**Issue by erikbosch** [eclipse/kuksa.val.feeders#131]
Our naming of feeders/providers is quite inconsistent. There is a plan to split the KUKSA repos and as part of that it could be good to align what names should be. As of today naming pattern in source, readme and docker containers often varies. It is partially described at https://github.com/eclipse/kuksa.val/wiki/KUKSA-Naming-Guidelines

Examples:
- In https://github.com/eclipse/kuksa.val.feeders/tree/main/gps2val we call it `GPS Feeder`
- In https://github.com/eclipse/kuksa.val.feeders/tree/main/gps2val it is described how you can build a docker container `gpsd_feeder`
- But in githib you can download it as `gps` (see https://github.com/eclipse/kuksa.val.feeders/pkgs/container/kuksa.val.feeders%2Fgps)

The image below show how inconsistent naming are for Docker containers. Changing name when moving would be good, as users then anyway will need to select a new repo to download latest container

![image](https://github.com/eclipse/kuksa.val.feeders/assets/30996601/c0b6b297-3440-43e5-b22a-1125450bdcfc)

**Comment by lukasmittag** [comment]
I think with the move we should switch to either <protocol>2val for everything or <protocol>_provider
