### ISSUE TITLE
Naming of components that will be split out for repo move

### ISSUE THREAD

**Issue by lukasmittag** [eclipse/kuksa.val.feeders#142]
With the move to the new organization https://github.com/eclipse-kuksa we want to split out some components of this repo. Like the ```dbc2val``` feeder. While doing this changes in the naming can easily be made. Therefore we need a discussion around the naming. 

What requirements we have:
* It should be generic so that the naming will allow an easy and meaningful addition of new components
* renaming  ```feeders``` to ```providers```

What we suggest is something like:
* <protocol/format>-provider -> would mean for ```dbc2val``` renaming to ```can-provider``` 
* kuksa-<protocol/format>-provider -> would mean for ```dbc2val``` renaming to ```kuksa-can-provider``` 

Second option would be consistnet with the current naming of the components in  https://github.com/eclipse-kuksa

**Comment by SebastianSchildt** [comment]
See also https://github.com/eclipse/kuksa.val/wiki/Proposal-for-splitting-of-KUKSA.val , even though nothing about providers yet.

To be consistent with the already defined
 - kuksa-python-sdk
 - kuksa-android-sdk
 - etc.

I suggest 
 - kuksa-can-provider
 - kuksa-gps-provider
 - etc.

The question for the dbc provider would stillt be `kuksa-can-provider` or `kuksa-dbc-provider`, whereas the latter is more specific, while the former might be more obvious

**Comment by erikbosch** [comment]
I think `kuksa-can-provider` makes sense, as we already supports variants like j1939. Then, if needed in the future we could add new repos with suffixes if we would create totally different implementations for CAN, like `kuksa-can-provider-rust` (If we decide to implement it in Rust) or `kuksa-can-provider-xxx` (If we use `xxx`config files and they are so different that it does not make sense to have it as just a variant) 

Then we have `csv_provider` where I believe `kuksa-csv-provider` makes sense. For `replay` I am a bit more uncertain - does anyone use it or shall we consider it deprecated and just leave it in the old repo (which later will be locked?), or call it something like `kuksa-val-server-replay`

**Comment by SebastianSchildt** [comment]
Replay I consider deprecated, we have CSV provider now that basically can do the same, maybe even better

We MIGHT still want to have kuksa-misc-provider or kuksa-incubation-provider for experiments, but I am not 100% sure about that

**Comment by erikbosch** [comment]
But CSV provider is still just for Databroker, and replay for Server, or? 

That off course does not prevent us from considering replay as deprecated, keep it in the old repo and if there is need for more advanced replay functionality for kuksa-val-server then implement that in csv-provider instead.

**Comment by erikbosch** [comment]
Migration finished, closing this
