### ISSUE TITLE
build dds-provider fail

### ISSUE THREAD

**Issue by TTT-MAC** [eclipse/kuksa.val.feeders#159]
Excuse me，When I tried to build the dds provider locally, Run "idlc -l py -I std_msgs/msg -x final NavStatFix.idl" in the generate_py_dataclass.sh file，Alerts me to idlc tool-related issues，Where do I get the idlc tool to convert *.idl files to python files? Are there any recommended open source tools？

best regards.

**Comment by lukasmittag** [comment]
Hey, have you done theses steps from https://github.com/eclipse/kuksa.val.feeders/tree/main/dds2val readme? 
```
chmod u+x ddsproviderlib/idls/generate_py_dataclass.sh
./ddsproviderlib/idls/generate_py_dataclass.sh
```

**Comment by erikbosch** [comment]
You can compare with how [continuous integration](https://github.com/eclipse/kuksa.val.feeders/blob/main/.github/workflows/kuksa_dds_feeder.yml) is setup:

```
    - name: Run dds tests
      run: |
        cd dds2val
        # Note - if relying on kuksa-client pre-releases you must use --pre on the line below
        pip3 install --no-cache-dir -r requirements/requirements.txt -r requirements/requirements-kml.txt -r requirements/requirements-test.txt
        ./ddsproviderlib/idls/generate_py_dataclass.sh
        python -m pytest tests/*
```

It is `cyclonedds` that provides `idlc` in CI, added by [requirements.txt](https://github.com/eclipse/kuksa.val.feeders/blob/main/dds2val/requirements/requirements.txt)

**Comment by TTT-MAC** [comment]
Okay，Problem solved, thank you for your reply!

best regards！

**Comment by lukasmittag** [comment]
closing since solved :)
