### ISSUE TITLE
Databroker Datapoint registration in DBC feeder

### ISSUE THREAD

**Issue by SebastianSchildt** [eclipse/kuksa.val.feeders#39]
The first version of the databroker integration was able to register VSS datapoints in databroker.

With the adoption of python library this is not possible currently (as the python lib depends on an interface that does not provide this method yet), so it is dependant on a databroker deployment that is already provisioned with correct VSS model (similar to the val-server behavior).

Once the API used by the python lib can register datapoints and support is added to the lib, we shall revisit this feature again in DBC feeder.

Might also be related to #36  : If we use a standard overlay for mapping, that basically is already a valid VSS model in its own right. So it might be an alternative pattern to be able to feed that to databroker, if so desired (similar to how databroker currently is able to process one single JSON during startup. If it gains a method/API to process further overlays during runtime, that might be an alternative)

**Comment by erikbosch** [comment]
So the current call to `set_metadata` at https://github.com/eclipse/kuksa.val.feeders/blob/main/dbc2val/databroker.py#L68 does not actually work as of today?

**Comment by erikbosch** [comment]
I created https://github.com/eclipse/kuksa.val/issues/485 to track if/when it is implemented in KUKSA.val. Nothing can be done in Feeder until then

**Comment by erikbosch** [comment]
Dbcfeeder behavior changed in #60 - now just checking if signal is registered

**Comment by erikbosch** [comment]
Think nothing will happen here, closing it
