### ISSUE TITLE
No master/main builds for DBC and GPC feeder containers

### ISSUE THREAD

**Issue by SebastianSchildt** [eclipse/kuksa.val.feeders#40]
We do not build/push a master/main tag

That should change

**Comment by SebastianSchildt** [comment]
Issue for GPS Feeder fixed, can push to GHCR now  https://github.com/eclipse/kuksa.val.feeders/actions/runs/4191983806
@int0x27

**Comment by sophokles73** [comment]
For dbc2val there also seems to be an image based on main available.
https://github.com/eclipse/kuksa.val.feeders/pkgs/container/kuksa.val.feeders%2Fdbc2val/113595981?tag=main

Maybe this issue can be closed? @SebastianSchildt

**Comment by SebastianSchildt** [comment]
Right, closing now.
