### ISSUE TITLE
Support authorization in DBC Feeder

### ISSUE THREAD

**Issue by lukasmittag** [eclipse/kuksa.val.feeders#66]
Maybe give the ability to say 'I want to use dbc feeder with authorization' and 'No, I don't want authorization'
For authorization what needs to be done is:
* Add new parser argument here: https://github.com/eclipse/kuksa.val.feeders/blob/a95ad4c90c11c3c90185b4fc4dfe71dd4e7f3b1c/dbc2val/dbcfeeder.py#L386
* Extend to enforce authorization if wanted : https://github.com/eclipse/kuksa.val.feeders/blob/a95ad4c90c11c3c90185b4fc4dfe71dd4e7f3b1c/dbc2val/dbcfeeder.py#L173
* Provide the right token file. Maybe add a parser/config argument for this. And think about a good default token (allow everything?or is it too much)

**Comment by erikbosch** [comment]
Work ongoing in https://github.com/eclipse/kuksa.val.feeders/pull/74

**Comment by erikbosch** [comment]
#74 merged, closing this one.

Note that solution relies on kuksa-client v0.4 which so far only exist as pre-release
