### ISSUE TITLE
Support authorization in GPS feeder

### ISSUE THREAD

**Issue by lukasmittag** [eclipse/kuksa.val.feeders#67]
What needs to be done:
* Give the ability to choose whether you want to use authoriaztion or not
* Extend here (uses kuksa client): https://github.com/eclipse/kuksa.val.feeders/blob/a95ad4c90c11c3c90185b4fc4dfe71dd4e7f3b1c/gps2val/gpsd_feeder.py#L45
* Think of a good default token (allow everything?)

**Comment by erikbosch** [comment]
Will be fixed by #84

**Comment by erikbosch** [comment]
PR merged, closing this one
