### ISSUE TITLE
Replay not working anymore

### ISSUE THREAD

**Issue by lukasmittag** [eclipse/kuksa.val.feeders#69]
The replay function only works for KUKSA.val server. Maybe it should be dropped? Definitely should be clearly marked outdated.

**Comment by SebastianSchildt** [comment]
If we "Update" (i.e. maybe redo) this, then this is worth a look: https://github.com/eclipse/kuksa.val/issues/366

**Comment by erikbosch** [comment]
Replay functionality (for KUKSA Server) was fixed as part of #117. That it does not support Databroker (and Databroker cannot create logs to be used by Replay) is a limitation rather than a bug. So shall we possibly close this one?

**Comment by SebastianSchildt** [comment]
I suggest we consider replay legacy/deprecated now and closing this report? For databroker, CSV provider provides pretty much the same functionality and is supported.

(Other) opinions @erikbosch  @lukasmittag ?
