### ISSUE TITLE
DDS provider update Listerner vs waitset

### ISSUE THREAD

**Issue by AkhilTThomas** [eclipse/kuksa.val.feeders#71]
There are two ways to fetch data from cyclonedds-python. Using waitsets or Listeners. Current implementation is using Listeners. Check the possibility of using waitsets and document which method is better and why

**Comment by erikbosch** [comment]
Is this one still relevant. If so I can "migrate" it to the new dds repo, if not I will close it.

**Comment by AkhilTThomas** [comment]
> Is this one still relevant. If so I can "migrate" it to the new dds repo, if not I will close it.

Since on one is requesting it, This can be closed. If needed a new ticket can be created to implement this.
